### PR TITLE
EventManager v3 compat

### PR DESCRIPTION
**Pull request by robob4him**
Changes needed for v3 event manager

### CODE REVIEW

**Comment by ojhaujjwal** [comment]
revise composer.json as well including the support for v3.

**Comment by robob4him** [comment]
@ojhaujjwal Ah, right. A question then @mtymek. Should it be >=2.6.0, >=3.0.0, or some other version configuration?

**Comment by mtymek** [comment]
Thanks for this PR!

In order to make it work under both major version, please use this constraint: `^2.6.0 || ^3.0.1`. Also, please fix unit tests - they are failing at this moment.

**Comment by robob4him** [comment]
@mtymek NP.

I've got a bit of a workaround I thought I'd throw at you before I submit the test change.

The test 'testComposeTriggersEvents' looks like it's made to assert the number and order of calls to the EventManager. Thing is, ZF3 changes event triggering so that there's no initial argument to verify. So instead of $em->trigger(string, ComposerEvent) it's just $em->triggerEvent(ComposerEvent) and I can't think of a way to make it more testable other than making changes to the test to:

* Create normal EventManager
* Attach a callback to each ComposerEvent expected to trigger that:
  * Asserts an instance of ComposerEvent
  * Stores in a variable that the event was triggered
* Asserts the variable has an expected content

I'm wondering if that seems acceptable to you or if you had any ideas. I can submit with those changes if I'm not making any sense, too.

**Comment by mtymek** [comment]
I tried to convert that tests to Prophecy and then mock the calls like this:

```php
        $em->triggerEvent(Argument::that(function ($event) {
                return $event instanceof ComposerEvent
                    && $event->getName() == ComposerEvent::EVENT_COMPOSE_POST;
            }))->shouldBeCalled();
```

Unfortunately it just does not work, same goes for PHPUnit's old mocking engine. 
So, your solution is not bad at all :-) I'll do more tests and merge it as it is.

**Comment by mtymek** [comment]
I fixed coding style issues and merged this to `master` (without tagging new stable version). I'm going to test it properly tomorrow, but it wouldn't hurt if you could set required version to `dev-master` and test it as well. I'll tak v1.2 afterwards.
Thanks!

**Comment by robob4him** [comment]
@mtymek, works for me. Rendered and our internal tests succeeded. I'm good!

**Comment by mtymek** [comment]
This changeset was already merged.

**Pull request closed without merging**
